### ISSUE TITLE
Provide Directory relation for Module

### ISSUE THREAD

**Issue by lostiniceland** [jqassistant-plugin/jqassistant-typescript-plugin#15]
In order to model a certain folder structure (like hexagonal architecture in Java) it would be easier to have corresponding directory relation for a ts module.

`(:Directory)-[:CONTAINS]->(:TS:Module)` 

This way it would be easy to mark directories when then containing modules have a certain DEPENDS_ON relation.

**Comment by SebastianWendorf** [comment]
Actually, we just released a new version that should solve this problem (1.0.0-RC1 on Maven, 1.0.0 on npm). The directory structure of the project should now be properly represented in the graph. The meta model in the README also got updated to reflect these changes.

May I ask what kind of directory structures you're testing for? This would be helpful to us for testing the plugin and evaluating its capabilities.

**Comment by lostiniceland** [comment]
Considering an Angular application with a structure like the following
```
.
└── src/
    └── app/
        ├── shared/
        │   ├── ui/
        │   │   ├── some.component.ts
        │   │   └── ...
        │   └── validation/
        │       └── ...  
        ├── context-a/
        │   └── ... 
        └── context-b/
            └── ...
```
We want to make sure that nothing from ` context-a`  depends on ` context-b`  and vice-versa. Everything inside a context is only allowed to access `shared`, while `shared` is not allowed to depend on any context.

After checking the meta model, I am not sure if this is even possible because I just realized that a Module has no knowledge of what it imports (only what it exports).
Regarding the folder structure, even with the new version, I can only see the file-level information and would need to fallback to regex or other filters to extract the folder structure. Possible, but a little cumbersome.
I might also miss something in the meta model.

**Comment by SebastianWendorf** [comment]
Thanks for the feedback! 
Currently dependencies are registered on a statement/expression level. This means that all imports (as long as they are not unused imports) should be reflected in the `DEPENDS_ON` relationships of the module. So you should be able to use these relationships to solve your case.

The directory nodes are actually generated, they are just not directly represented in the meta model. This was done, because the `:Directory` and `:File` nodes and their relationships are considered part of the jQA Core Framework and not this particular plugin.
The only addition/change that was made here by the plugin, is the introduction of the `:File:Local` "specialization" of the default `:File` nodes that always holds an `absoluteFileName`.
I will modify the README to better reflect these details.

**Comment by lostiniceland** [comment]
Closing since already sufficiently implemented.
