### ISSUE TITLE
Should DEPENDS_ON cardinality between Module and ExternalModule include ExternalDeclarations?

### ISSUE THREAD

**Issue by JohT** [jqassistant-plugin/jqassistant-typescript-plugin#33]
Hey 👋,

i've recognized that `ExternalDeclaration` cardinality isn't included in the sum of cardinalities of the `DEPENDS_ON` relationship between a `Module` and an `ExternalModule`. Everything else that `Module` declares or depends on seems to be included as i'd expect.

Here is a picture of an example from the analysis of [ts-output-react-router.json](https://github.com/jqassistant-plugin/jqassistant-typescript-plugin/files/14731990/ts-output.json) with the [example-query.cypher](https://github.com/jqassistant-plugin/jqassistant-typescript-plugin/files/14731994/example-query.cypher.txt):

<img width="500" alt="example-graph" src="https://github.com/jqassistant-plugin/jqassistant-typescript-plugin/assets/7671054/79ccbfa5-8a60-41ec-b1fc-554f1a87e49e">

- `DEPENDS_ON` relationships are displayed with their cardinalities
- The orange `ìndex.ts` node is the `Module`
- The grey `history.ts` node is the `ExternalModule`
- The blue and green nodes are elemens that are declared by `Module` and depend on `ExternalModule`. Their cardinalities sum up to 4 which equals the cardinality between `Module` and `ExternalModule`.
- The purple nodes are labeled `ExternalDeclaration`. They are exported by the `ExternalModule` and used within the `ExternalModule`. Their cardinalities (2x2=4) between `Module` and `ExternalDeclaration` are **not** included in the sum of cardinalities between `Module` and `ExternalModule`.

To rephrase that in cypher language 😀:

- `module_rel.cardinality` of `(source:TS:Module)-[module_rel:DEPENDS_ON]->(target:TS:ExternalModule)` contains the **sum of cardinalities** between those modules
- The sum above contains all `element_rel.cardinality` of `(source)-[:DECLARES]->(element)-[element_rel:DEPENDS_ON]->(target)`
- The sum above **does not contain** `declaration_rel.cardinality` of `(source)-[declaration_rel:DEPENDS_ON]->(declaration:ExternalDeclaration)<-[:EXPORTS]-(target)`

What is reason for leaving out external declaration dependencies between modules or is this unintentional?

Thank you very much 🙏,
Johannes

By the way: Awesome plugin for Typescript 👍. I'm trying to integrate it into my [code-graph-analysis-pipeline](https://github.com/JohT/code-graph-analysis-pipeline/pull/112).

**Comment by SebastianWendorf** [comment]
Hi, thanks for bringing this up! The behavior you observed is intentional.
The "original" dependencies that got detected in the code are the ones between the module declarations and the external declarations. These dependencies are then propagated on *both* sides. This means if a declaration depends on an external declaration, it also depends on the external module (with the same cardinality). Similarly does the declaring module depend on the external declarations (using aggregating the cardinalities of all declarations). Finally these dependencies are then aggregated, forming a dependency between the declaring module and the external module.

Here is an example roughly outlining how dependencies are aggregated in the graph:
[Dependency Example.drawio.pdf](https://github.com/jqassistant-plugin/jqassistant-typescript-plugin/files/14740439/Dependency.Example.drawio.pdf)

I will adjust the documentation to better reflect this behavior.

**Comment by JohT** [comment]
Hi @SebastianWendorf, 

awesome. Now this is much clearer for me. Thanks a lot 🙏. I'll close this issue.
